export const tipoCategorias = [
  {
    icon: require("../assets/icons/ong.png"),
    title: "ONGs",
  },
  {
    icon: require("../assets/icons/cachorro.png"),
    title: "Cachorros",
  },
  {
    icon: require("../assets/icons/gato.png"),
    title: "Gatos",
  },
  {
    icon: require("../assets/icons/ave.png"),
    title: "Aves",
  },
  {
    icon: require("../assets/icons/cavalo.png"),
    title: "Cavalo",
  },
  {
    icon: require("../assets/icons/coelho.png"),
    title: "Coelho",
  },
];

export const dadosAnimais = [
  {
    id: 1,
    img: require("../assets/images/animals/dog01.png"),
    nome: "Simba",
    idade: "5 anos",
    sexo: "Macho",
    especie: "Vira-lata",
    localidade: "Campina Grande - PB (2km)",
    isVacinado: "Sim",
    favorito: false,
  },
  {
    id: 2,
    img: require("../assets/images/animals/dog02.png"),
    nome: "Flora",
    idade: "2 anos",
    sexo: "Fêmea",
    especie: "Vira-lata",
    localidade: "Campina Grande - PB (4km)",
    isVacinado: "Sim",
    favorito: false,
  },
  {
    id: 3,
    img: require("../assets/images/animals/dog03.png"),
    nome: "Flor",
    idade: "5 anos",
    sexo: "Fêmea",
    especie: "Vira-lata",
    localidade: "Campina Grande - PB (3km)",
    isVacinado: "Sim",
    favorito: false,
  },
  {
    id: 4,
    img: require("../assets/images/animals/dog04.png"),
    nome: "Canela",
    idade: "1 anos",
    sexo: "Fêmea",
    especie: "Vira-lata",
    localidade: "Campina Grande - PB (1km)",
    isVacinado: "Sim",
    favorito: false,
  },
  {
    id: 5,
    img: require("../assets/images/animals/dog05.png"),
    nome: "Pitico",
    idade: "1 anos",
    sexo: "Macho",
    especie: "Vira-lata",
    localidade: "Campina Grande - PB (2km)",
    isVacinado: "Sim",
    favorito: false,
  },
  {
    id: 6,
    img: require("../assets/images/animals/dog06.png"),
    nome: "Filó",
    idade: "1 anos",
    sexo: "Fêmea",
    especie: "Vira-lata",
    localidade: "Campina Grande - PB (4km)",
    isVacinado: "Sim",
    favorito: false,
  },
  {
    id: 7,
    img: require("../assets/images/animals/dog07.png"),
    nome: "Thor",
    idade: "4 anos",
    sexo: "Macho",
    especie: "Vira-lata",
    localidade: "Campina Grande - PB (2km)",
    isVacinado: "Sim",
    favorito: false,
  },
  {
    id: 8,
    img: require("../assets/images/animals/dog08.png"),
    nome: "Pretinho",
    idade: "5 anos",
    sexo: "Macho",
    especie: "Vira-lata",
    localidade: "Campina Grande - PB (5km)",
    isVacinado: "Sim",
    favorito: false,
  },
];

export const intituicoes = [
  {
    img: "",
    nome: "Centro de Zoonose",
    telefone: "(83) 3077-0107",
    endereco: "R. Isolda Barros Torquarto, s/n",
    cidade: "Campina Grande",
    estado: "Paraíba",
    bairro: "Bodocongó",
  },
];
